package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.27 20:16:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValuuttaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi49 */
  @Test
  public void testRekisteroi49() {    // Valuutta: 49
    Valuutta bitcoin = new Valuutta(); 
    assertEquals("From: Valuutta line: 51", 0, bitcoin.getTunnusNro()); 
    bitcoin.rekisteroi(); 
    Valuutta ethereum = new Valuutta(); 
    ethereum.rekisteroi(); 
    int n1 = bitcoin.getTunnusNro(); 
    int n2 = ethereum.getTunnusNro(); 
    assertEquals("From: Valuutta line: 57", n2-1, n1); 
    </pre
  } // Generated by ComTest END
}